### PR TITLE
Updated URL schema

### PR DESCRIPTION
**Pull request by bbvmedia**
Updated URL schema and descriptive text in index.html and gettingstarted.html.

### CODE REVIEW

**Comment by woubuc** [comment]
@bbvmedia don't forget to update the random url function and the example parts in main.coffee

**Comment by bbvmedia** [comment]
@woubuc Hi, just saw your note about main.coffee. I've updated that file as well.

**Comment by woubuc** [comment]
@bbvmedia did you compile the coffeescript?

**Comment by bbvmedia** [comment]
@woubuc Yes, the CoffeeScript has been compiled and included in this latest commit.

**Pull request merged**
