### PR TITLE
Bounty #14

### PR DESCRIPTION
**Pull request by jkaan**
Added return formats:
- YAML
- CSV
- XML

### CODE REVIEW

**Comment by woubuc** [comment]
It seems the files /src/app.coffee and /app.js don't match. Did you perhaps add your changes to /app.js directly, instead of to /src/app.coffee?

**Comment by jkaan** [comment]
I completely forgot about the changes I made to /app.js. The commit I just did a few seconds ago now also has the changes added to the src/app.coffee file !

**Comment by woubuc** [comment]
You still need to add the content type header to the special endpoints in the coffee source, then it should be okay. I assume then that you just made the changes in app.js instead of editing the .coffee source file? 

It's important that the source code is correct, because when I or others work on it the .coffee file will be compiled and it will overwrite app.js with the compiled code from app.coffee and thus any changes in app.js that are not in app.coffee will be lost. 

So for the app itself it's actually required to work in the Coffeescript code and compile it, and to just not edit the .js files. You can use a tool like Koala to compile your Coffeescript code automatically when you save, so that both files stay up to date.

**Comment by jkaan** [comment]
Hey there!

I have just added the content type header to the special endpoints in the coffee source. I have also edited a Gulpfile.js. This handles the compiling in a way that I'm most used to. This should also make it easier for other developers to start working on the Coffeescript code, without having to recompile themselves. This should help in avoiding the mistake I made of editing the JS file.

**Pull request merged**
