### PR TITLE
New datatypes

### PR DESCRIPTION
**Pull request by jkaan**
- Added 6 new datatypes
- Parameters given to datatypes can now also be alphabetic instead of only numeric, this was needed for the color datatype and probably needed for more datatypes to be added

### CODE REVIEW

**Comment by woubuc** [comment]
Great, adding string parameters will no doubt come in useful for new datatypes :-)

A few things need to be adjusted though.

- Could you add a check to see which parameter type is expected by the datatype, and only pass along the parameter if it's of the correct type, so that there are no conflicts with wrong parameter types
- I see some of your type_map properties are strings, they should be arrays
- Please put your 'require's at the top of the script, not inside a function. Requiring inside a function causes the module to be (re)loaded synchronously every time the function is called, slowing down the script execution.
- This one is a personal preference, but while you're changing the type_maps to arrays, could you add 'colour' as an alt for color?

**Comment by jkaan** [comment]
I have adjusted all but the first point. I'm not 100% clear on that one.

Do you mean checking if it's the type is correct before calling the value function of the datatype or inside it?

I think just checking if the correct type is being given to the datatype itself is properly the best way.

**Comment by woubuc** [comment]
I would add it the check to the part where you assign the parameter, where you check `if parseInt`, change the `else` to something like `else if type.parameter_type isnt 'numeric'`. That way, if the parameter isn't numeric but the datatype expects a numeric parameter, it just stays null and the parameter won't be used (and thus it will fallback to the default parameter).

Of course if you have a different idea, feel free to do it your way :-)

**Comment by jkaan** [comment]
Oh that sounds good as well. Maybe it's even better to do it that way. Is it a problem that I change the parameter_type to `number` instead of `numeric` since the first is what is being returned by the `typeof` operator in JavaScript

**Comment by woubuc** [comment]
Not a problem, go ahead. `number` actually makes more sense :-)

**Comment by jkaan** [comment]
I have implemented the things you mentioned. Let me know what you think!

**Pull request merged**
